// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhkfheutelgfmtnqifcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oa2ZoZXV0ZWxnZm10bnFpZmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTQ3OTksImV4cCI6MjA3Mjg5MDc5OX0._VdGQ3ITMGtokEWkSmwDBFo5LAU5GFmbPyrFe0oAd78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});